id: IF619A019
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:42:10+00:00'
last_modified: '2022-06-08T10:00:41.835599+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W18616
  title: སངས་རྒྱས་ཀྱི་རྣམ་ཐར་བདེ་བ་གཤེགས་པའི་སྤྱོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    29D1:
      image_group_id: I1KG10860
      title: ''
      total_pages: 540
      order: 1
      base_file: 29D1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
